snapshot 2026-10-09T18:00:00.635093+00:00

diff --git a/znew.in b/znew.in
--- a/znew.in
+++ b/znew.in
@@ -37,7 +37,6 @@ Options:
   -t     Test the new files before deleting originals.
   -v     Verbose; display name and statistics for each file compressed.
   -9     Use the slowest compression method (optimal compression).
-  -P     Use pipes for the conversion to reduce disk space usage.
   -K     Keep a .Z file when it is smaller than the .gz file; implies -t.
       --help     display this help and exit
       --version  output version information and exit
@@ -45,7 +44,6 @@ Options:
 Report bugs to <bug-gzip@gnu.org>."
 
 check=0
-pipe=0
 opt=
 files=
 keep=0
@@ -83,7 +81,8 @@ case "$opt" in
   *K*) keep=1; check=1; opt=`printf '%s\n' "$opt" | sed 's/K//g'`
 esac
 case "$opt" in
-  *P*) pipe=1; opt=`printf '%s\n' "$opt" | sed 's/P//g'`
+  *P*) opt=`printf '%s\n' "$opt" | sed 's/P//g'`
+       echo >&2 "$0: warning: obsolete option -P ignored"
 esac
 if test -n "$opt"; then
   opt="-$opt"
@@ -98,74 +97,57 @@ for i do
     res=1; continue
   fi
   test $keep -eq 1 && old=`wc -c < "$n.Z"`
-  if test $pipe -eq 1; then
-    if 'gzip' -d < "$n.Z" | 'gzip' $opt > "$n$ext"; then
-      # Copy file attributes from old file to new one, if possible.
-      touch -r"$n.Z" -- "$n$ext" 2>/dev/null
-      chmod --reference="$n.Z" -- "$n$ext" 2>/dev/null
+  if test $check -eq 1; then
+    if test -z "$mktemp_status"; then
+      command -v mktemp >/dev/null 2>&1
+      mktemp_status=$?
+    fi
+    if { if test $mktemp_status -eq 0; then
+           tmp=`mktemp "$n.XXXXXXXXX"`
+         else
+           tmp=$n.$$
+           (umask 77; set -C; > "$tmp")
+         fi; } && cp -p "$n.Z" "$tmp"; then
+      :
     else
-      printf '%s\n' "error while recompressing $n.Z"
+      printf '%s\n' "cannot backup $n.Z"
       res=1; continue
     fi
+  fi
+  if 'gzip' -d "$n.Z"; then
+    :
+  else
+    test $check -eq 1 && mv "$tmp" "$n.Z"
+    printf '%s\n' "error while uncompressing $n.Z"
+    res=1; continue
+  fi
+  if 'gzip' $opt "$n"; then
+    :
   else
     if test $check -eq 1; then
-      if test -z "$mktemp_status"; then
-        command -v mktemp >/dev/null 2>&1
-        mktemp_status=$?
-      fi
-      if { if test $mktemp_status -eq 0; then
-             tmp=`mktemp "$n.XXXXXXXXX"`
-           else
-             tmp=$n.$$
-             (umask 77; set -C; > "$tmp")
-           fi; } && cp -p "$n.Z" "$tmp"; then
-        :
-      else
-        printf '%s\n' "cannot backup $n.Z"
-        res=1; continue
-      fi
-    fi
-    if 'gzip' -d "$n.Z"; then
-      :
+      mv "$tmp" "$n.Z" && rm -f "$n"
+      printf '%s\n' "error while recompressing $n"
     else
-      test $check -eq 1 && mv "$tmp" "$n.Z"
-      printf '%s\n' "error while uncompressing $n.Z"
-      res=1; continue
+      # compress $n  (might be dangerous if disk full)
+      printf '%s\n' "error while recompressing $n, left uncompressed"
     fi
-    if 'gzip' $opt "$n"; then
-      :
-    else
-      if test $check -eq 1; then
-        mv "$tmp" "$n.Z" && rm -f "$n"
-        printf '%s\n' "error while recompressing $n"
-      else
-        # compress $n  (might be dangerous if disk full)
-        printf '%s\n' "error while recompressing $n, left uncompressed"
-      fi
-      res=1; continue
-    fi
+    res=1; continue
   fi
   test $keep -eq 1 && new=`wc -c < "$n$ext"`
   if test $keep -eq 1 && test `expr \( $old + $block - 1 \) / $block` -lt \
                               `expr \( $new + $block - 1 \) / $block`; then
-    if test $pipe -eq 1; then
-      rm -f "$n$ext"
-    else
-      mv "$tmp" "$n.Z" && rm -f "$n$ext"
-    fi
+    mv "$tmp" "$n.Z" && rm -f "$n$ext"
     printf '%s\n' "$n.Z smaller than $n$ext -- unchanged"
 
   elif test $check -eq 1; then
     if 'gzip' -t "$n$ext" ; then
       rm -f "$tmp" "$n.Z"
     else
-      test $pipe -eq 0 && mv "$tmp" "$n.Z"
+      mv "$tmp" "$n.Z"
       rm -f "$n$ext"
       printf '%s\n' "error while testing $n$ext, $n.Z unchanged"
       res=1; continue
     fi
-  elif test $pipe -eq 1; then
-    rm -f "$n.Z"
   fi
 done
 exit $res
