Frozen autocommit 2024-01-09 07:13:46.355645

diff --git a/tests/list b/tests/list
--- a/tests/list
+++ b/tests/list
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Exercise the --list option.
 
-# Copyright 2016-2023 Free Software Foundation, Inc.
+# Copyright 2016-2024 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -27,5 +27,14 @@ gzip -9 in || fail=1
 gzip -l in.gz >out1 || fail=1
 gzip -l in.gz | cat >out2 || fail=1
 compare out1 out2 || fail=1
+
+echo '' >small || framework_failure_
+gzip small || fail=1
+cat small.gz small.gz >smallx2.gz || framework_failure_
+gzip -l smallx2.gz >smallout || fail=1
+case $(cat smallout) in
+  *' 2 '*' smallx2') ;;
+  *) cat smallout; fail=1;;
+esac
 
 Exit $fail
